### PR TITLE
Some refactoring

### PR DESCRIPTION
**Pull request by TiberiumN**
I've done some refactoring, but I didn't check if my version works or not (at least it compiles):)
Can you try it?

### CODE REVIEW

**Comment by StandB** [comment]
Holy crap this is awesome. U made this code look way better. I'm pretty new to Nim and programming itself so thanks for the help man.

**Comment by TiberiumN** [comment]
@StandB I'm relatively new to Nim too (roughly one month)

**Comment by StandB** [comment]
oh that's cool, it has been a week for me.

**Comment by TiberiumN** [comment]
@StandB but yeah, I'm not new to programming (I've used Python)

**Comment by StandB** [comment]
For how long?

**Comment by TiberiumN** [comment]
@StandB oh, I can't remember :) Maybe like 2-3 months. But I don't have any big projects in Python, so I'm not a professional Python programmer (maybe junior level :D).

**Comment by StandB** [comment]
oh damn, that's not long at all.

**Comment by StandB** [comment]
anyway, thanks for doing this lol, u are awesome.

**Comment by StandB** [comment]
hit me up if u ever need a newb for a project :p

**Pull request merged**
